examples/collections.yml, examples/services.yml, opentaxii/cli/persistence.py
OpenTAXII uses anyconfig to parse configiration files for creating services and collections. OpenTAXII expects to get list-like object from anyconfig.
But anyconfig is designed to return dict-like object. So latest version of anyconfig raises exception
"ValueError" when parses examples of configuration files.
```
./bin/opentaxii-create-collections -c services.yml
<<cut>>
ValueError: dictionary update sequence element #0 has length 8; 2 is required
```
anyconfig binary fails as well
```
./bin/anyconfig_cli -I yaml services.yml
<<cut>>
ValueError: dictionary update sequence element #0 has length 8; 2 is required
```
To avoid this error need to use old version of anyconfig.
So config files should be fixed (make it dict-like to be compatible with anyconfig)
It can be done as
`{ID1: …
=> Fixed anyconfig exception while loading of configuration files

docs/auth.rst
taxii-poll appears to need --host and --port to be separate args.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eclecticiq/opentaxii/65)
=> Split host and port args in taxii-poll usage doc

README.md
There was a space between your link text and the link itself, so the markdown wasn't formatting
It bugged me, so it's fixed now!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eclecticiq/opentaxii/74)
=> fix: Touch up index.md link syntax

docs/docker.rst
`run` command is missing in `docs/docker.rst`#L44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eclecticiq/opentaxii/87)
=> Fixed a typo in docs/docker.rst

.travis.yml, requirements-dev.txt
- Test more Python versions
- Avoid duplicate jobs for PRs/branches by restricting branches to test
- Use `pytest-pythonpath` instead of setting `PYTHONPATH`
=> work on travis-ci config

tests/services/test_inbox.py
when a collection is part of more than 1 service, the collection's
services would be overwritten instead of added.
weirdly, this only seemed to cause issues in python 3.5. I have no idea
why the tests aren't flaky in other python versions.
=> fix flaky tests

docker/entrypoint.sh
Our Docker setup has a mistake in which the environment variable `OPENTAXII_CONFIG` isn't being passed to the main process of the image, leading the gunicorn process (or whatever CMD the user provides) to just use the default config values.
By exporting the variable we make sure that it does actually get passed to child processes.
Closes #127
=> Make sure OPENTAXII_CONFIG is set for main process in Docker

requirements.txt
This will not work until 4.3.1 is released: https://pypi.org/project/lxml/#history
It includes this bugfix which we want: https://bugs.launchpad.net/lxml/+bug/1814522
=> Add lxml to requirements, require 4.3.1 or newer

CHANGES.rst, docs/conf.py, opentaxii/_version.py
- Updated `CHANGES.rst`
- Bumped version in `opentaxii/_version.py`
- Make copyright year in docs dynamic
=> release version 0.1.11

CHANGES.rst
- date of 0.1.11 was wrong
- markdown formatting instead of RST for inline monospace blocks
=> fixes in changelog

opentaxii/config.py
> `__init__` method from base class %r is not called
=> Fix PyLint W0231

opentaxii/middleware.py, opentaxii/taxii/converters.py, opentaxii/taxii/http.py, opentaxii/taxii/services/handlers/collection_information_request_handlers.py, opentaxii/taxii/services/handlers/discovery_request_handlers.py, opentaxii/taxii/services/handlers/inbox_message_handlers.py, opentaxii/taxii/services/handlers/poll_fulfilment_request_handlers.py, opentaxii/taxii/services/handlers/poll_request_handlers.py, opentaxii/taxii/services/handlers/subscription_request_handlers.py, opentaxii/utils.py
> R1705: Unnecessary "else" after "return" (no-else-return)
Also, some functions had unexpected behavior if the TAXII version is not 10 or 11. I've added `raise ValueError('invalid version')`. It will help us to incrementally migrate on TAXII 2.0.
=> Fix PyLint R1705

opentaxii/server.py, opentaxii/taxii/services/handlers/inbox_message_handlers.py, opentaxii/taxii/services/handlers/subscription_request_handlers.py
> C1801: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
=> Fix PyLint C1801

docs/configuration.rst, opentaxii/config.py, opentaxii/defaults.yml, opentaxii/middleware.py, opentaxii/taxii/exceptions.py, opentaxii/taxii/services/abstract.py
Fix #18 with backward compatibility. Allow specifying alternative TAXII status type instead of "UNAUTHTORIZED". By default, use unauthorized how it recommend by spec (5.1 HTTP Responses as TAXII Status Messages).
=> allow to specify status for UNAUTHTORIZED

opentaxii/persistence/manager.py
Don't show Inbox service for users with read-only collection-level access permissions. Based on the discussion in https://github.com/eclecticiq/OpenTAXII/issues/152
=> check user can modify collection before advertising inbox service

docker/entrypoint.sh, docs/configuration.rst, opentaxii/cli/persistence.py, opentaxii/config.py, requirements.txt, tests/test_config.py
1. Allow to configure OpenTAXII with env vars
1. Drop `anyconfig` dependency. Fewer deps for OSS is always good.
1. Drop showing config in docker logs
Close #154
=> Env vars configuration

opentaxii/http.py, requirements-docker.txt
1. Upgrade Gunicorn to the version used in the EclecticIQ platform.
2. Rewrite root logger. New gunicorn sets the root logger (before it was missed accidentally): https://github.com/benoitc/gunicorn/pull/1958. We should rewrite it to force using the JSON handler.
=> Upgrade gunicorn

LICENSE.rst
Github doesn't auto-detect our current license due to the non-standard structure. This should fix that.
=> Update license for github license detection

.github/workflows/interrogate.yml, pyproject.toml, requirements-dev.txt, requirements-interrogate.txt
Get additional visiblity into status of docs
Docstrings are good for developers. We could use significantly more (and better, but that's hard to measure). This MR is a small attempt at introducing some visibility into the status of docstrings.
Uses [interrogate](https://interrogate.readthedocs.io/en/latest/) in a job coverage doesn't drop below the current value. Current coverage is 32.7%, with a setting that ignores coverage for a bunch of things. As time passes and docs improve, we might tighten the settings or increase the goal.
=> Get visibility into docstring coverage

CHANGES.rst, opentaxii/management.py, opentaxii/sqldb_helper.py, tox.ini
[Werkzeug 2.1](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0) broke our auth system. It now throws an exception instead of returning `None` when being passed non-json when calling `.to_json`. We depended on the previous behaviour.
This PR adds werkzeug<2.1 and >=2.1 to the tox matrix to ensure we support both cases and fixes the code.
=> Make sure werkzeug <2.1 and >=2.1 work correctly with auth

CHANGES.rst, opentaxii/_version.py, opentaxii/persistence/api.py, opentaxii/persistence/manager.py, opentaxii/persistence/sqldb/api.py, opentaxii/server.py, opentaxii/taxii2/entities.py, opentaxii/taxii2/utils.py, opentaxii/taxii2/validation.py, tests/taxii2/test_taxii2_manifest.py, tests/taxii2/test_taxii2_object.py, tests/taxii2/test_taxii2_objects.py, tests/taxii2/test_taxii2_sqldb.py, tests/taxii2/test_taxii2_utils.py, tests/taxii2/test_taxii2_versions.py, tests/taxii2/utils.py
This was in the wrong place. A parameter that's used to paginate the data coming from the database layer should be defined in the database layer, not the http layer :facepalm:
=> Move next_param handling into `OpenTAXII2PersistenceAPI`

.readthedocs.yaml, CHANGES.rst, docs/conf.py, opentaxii/_version.py
Updated .readthedocs.yaml to:
- Use more explicit build parameters
- explicitly use 'dirhtml' as output for pretty urls
Updated conf.py to:
- include 'sphinx_rtd_theme' and 'readthedocs-sphinx-search' extensions,
which were already included in docs/requirements.txt
- set theme to 'sphinx_rtd_theme'
- replace html config with sphinx_rtd_theme config
What this means:
- automatically populate sidebar instead of explicitly populating it
- sidebar should now contain all docs. now, you can navigate the docs
through that instead of having to navigate almost exclusively through
the 'next' and 'previous' buttons
=> Update build params for better navigation and to use sphinx_rtd_theme

.github/workflows/flake8.yml, .github/workflows/interrogate.yml, .github/workflows/publish.yml, .github/workflows/tox.yml, tests/conftest.py
The test  `tests/taxii2/test_taxii2_sqldb.py::test_delete_object[wrong collection]` returns `sqlite3.OperationalError: disk I/O error` with the env `py38-sqlalchemy14-werkzeuglt21-sqlite`.
Run all the tests with `tox -e py38-sqlalchemy14-werkzeuglt21-sqlite` on a fresh python environment. Delete the old environment if existing before.
Other failed attempts to reproduce it, eg it passed:
1. Reuse an existing environment
2. Split  the run in 2 sets `tox -e py38-sqlalchemy14-werkzeuglt21-sqlite -- tests/test_* <failed-test>`  and `tox -e py38-sqlalchemy14-werkzeuglt21-sqlite -- tests/taxii2/test_taxii2_sqldb.py`. Both succeeded.
3. Do not use coverage: `tox -e py38-sqlalchemy14-werkzeuglt21-sqlite -- --no-cov`
4. Increase log verbosity (see #264)
Another surprising fact is that using the …
=> Fix broken 3.8 SQLite test pipeline
